---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: density-app
  labels:
        app: density-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: density-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        target:
          kind: Service
          name: density-app
        metricName: flask_http_request
        targetValue: 10
