---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: density-app
  namespace: default
  labels:
        app: density-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: density-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi
