kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: density-app
  labels:
    app: density-app
spec:
  selector:
    matchLabels:
      app: density-app
  endpoints: 
  - port: density-app
