---

template_path: eks-network-loadbalancer.j2
parameters:

  DnsName: "density.jhallyburton.net"

sceptre_user_data:

  cluster_name: {{ stack_group_config.project_code }}
  vpc: {{ stack_group_config.vpc }}
  hosted_zone: {{ stack_group_config.hosted_zone }}
  subnets:
    - {{ stack_group_config.subnet01 }}
    - {{ stack_group_config.subnet02 }}
